apiVersion: v1
kind: Service
metadata:
  name: squid-exporter
  namespace: monitoring
  labels:
    app: squid-exporter
    release: ada
spec:
  ports:
  - port: 9301
    name: squid-port
    targetPort: 9301
    protocol: TCP
  selector:
    app: squid-exporter
    release: ada
