apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: monitoring
  labels:
    app: zkexpoerter
    release: ada
spec:
  ports:
  - port: 9141
    name: zkport
    targetPort: 9141
    protocol: TCP
  selector:
    app: zkexpoerter
    release: ada
